# Generated by Django 6.0 on 2026-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=100, verbose_name='Исходное выражение')),
                ('result', models.IntegerField(verbose_name='Результат операции')),
                ('time', models.CharField(default='22-01-2026 23:41:08', editable=False, max_length=50, verbose_name='Время создания')),
                ('expr_type', models.CharField(choices=[('Сложная операция', 'Сложная операция'), ('Простая операция', 'Простая операция')], verbose_name='Вид выражения')),
            ],
            options={
                'verbose_name': 'История вычислений',
                'verbose_name_plural': 'История вычислений',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='CharactersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на картинку')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('url', models.CharField(default='', max_length=100, verbose_name='Ссылка на игру')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='HobbyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Увлечение')),
            ],
            options={
                'verbose_name': 'Увлечение',
                'verbose_name_plural': 'Увлечения',
            },
        ),
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('url', models.CharField(max_length=100, verbose_name='Путь относительно главной')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PreformersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='PromptsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название промпта')),
                ('prompt', models.TextField(verbose_name='Промпт')),
                ('description', models.CharField(max_length=100, verbose_name='Описание промпта')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Статус одобрения')),
                ('created_at', models.CharField(default='22-01-2026 23:41:08', max_length=50, verbose_name='Время отправки промпта')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
            },
        ),
        migrations.CreateModel(
            name='RefsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=100, verbose_name='Ссылка на арт')),
                ('channel', models.CharField(max_length=100, verbose_name='Ссылка на художника')),
                ('author', models.CharField(max_length=100, verbose_name='Ник художника')),
                ('character', models.CharField(choices=[('1', 'Селфсона'), ('2', 'Старый скин')], default='Undefined', max_length=100, verbose_name='Имя ОС-а')),
            ],
            options={
                'verbose_name': 'Референс',
                'verbose_name_plural': 'Референсы',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('review', models.TextField(blank=True, default='', null=True, verbose_name='Текст рецензии')),
                ('review_time', models.CharField(default='22-01-2026', max_length=50, verbose_name='Дата создания рецензии')),
                ('genre', models.CharField(choices=[('Аниме', 'Аниме'), ('Фильм', 'Фильм'), ('Сериал', 'Сериал'), ('Мультик', 'Мультик')], null=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
            },
        ),
        migrations.CreateModel(
            name='SocialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соцсети')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на соцсеть')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
        migrations.CreateModel(
            name='StrHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=500, verbose_name='Изначальная строка')),
                ('digits', models.JSONField(blank=True, default=list, verbose_name='Цифры')),
                ('words', models.JSONField(blank=True, default=list, verbose_name='Оригинальные слова')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Исправленные слова')),
                ('others', models.JSONField(blank=True, default=list, verbose_name='Прочее')),
                ('time', models.CharField(default='22-01-2026 23:41:08', editable=False, max_length=50, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'История строк',
                'verbose_name_plural': 'История строк',
                'ordering': ['-time'],
            },
        ),
    ]
