# Generated by Django 6.0 on 2026-01-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharactersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на картинку')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('review', models.TextField(verbose_name='Рецензия')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на пост с рецензией')),
            ],
        ),
        migrations.AlterModelOptions(
            name='calchistory',
            options={'ordering': ['-time'], 'verbose_name': 'История вычислений', 'verbose_name_plural': 'История вычислений'},
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(max_length=500),
        ),
    ]
