# Generated by Django 6.0 on 2026-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='22-01-2026 23:41:17', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='22-01-2026 23:41:17', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='time',
            field=models.CharField(default='22-01-2026 23:41:17', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
