# Generated by Django 6.0 on 2026-01-24 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0002_alter_calchistory_time_alter_promptsmodel_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='24-01-2026 23:43:08', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='24-01-2026 23:43:08', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='24-01-2026', max_length=50, verbose_name='Дата создания рецензии'),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='time',
            field=models.CharField(default='24-01-2026 23:43:08', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.CreateModel(
            name='UserFeedbackAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Идея')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Чьё сообщение')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': 'Идеи',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Чьё сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=200, verbose_name='Страница с проблемой')),
                ('report', models.TextField(verbose_name='Текст репорта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Чьё сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
