# Generated by Django 6.0 on 2026-01-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0002_charactersmodel_reviewmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='url',
        ),
    ]
