# Generated by Django 6.0 on 2026-01-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0003_alter_calchistory_time_alter_promptsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название видео')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка на видео')),
                ('type', models.CharField(choices=[('Музыка', 'Музыка'), ('Видео', 'Видео'), ('Прочее', 'Прочее')], null=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Рандомные ссылки',
                'verbose_name_plural': 'Рандомные ссылки',
            },
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='24-01-2026 23:49:44', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='24-01-2026 23:49:44', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='time',
            field=models.CharField(default='24-01-2026 23:49:44', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
