# Generated by Django 6.0 on 2026-01-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0003_remove_reviewmodel_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactersmodel',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
    ]
