# Generated by Django 6.0 on 2026-01-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0005_randommodel_time_alter_calchistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='24-01-2026 23:52:17', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='24-01-2026 23:52:17', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='randommodel',
            name='time',
            field=models.CharField(default='24-01-2026 23:52:17', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='time',
            field=models.CharField(default='24-01-2026 23:52:17', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
