# Generated by Django 6.0 on 2026-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0005_charactersmodel_time_reviewmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='01-01-2026 21:00:53', max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='01-01-2026 21:00:53', max_length=50, verbose_name='Время создания'),
        ),
    ]
