# Generated by Django 6.0 on 2026-04-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0006_alter_calchistory_time_alter_promptsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialsmodel',
            options={'verbose_name': 'Ссылка на сервис', 'verbose_name_plural': 'Ссылки на сервисы'},
        ),
        migrations.AddField(
            model_name='socialsmodel',
            name='human_name',
            field=models.CharField(default='', max_length=100, verbose_name='Человеческое название сервиса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialsmodel',
            name='short_name',
            field=models.CharField(default='', max_length=100, verbose_name='Короткое название сервиса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='11-04-2026 02:21:13', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='11-04-2026 02:21:13', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='randommodel',
            name='time',
            field=models.CharField(default='11-04-2026 02:21:13', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='11-04-2026', max_length=50, verbose_name='Дата создания рецензии'),
        ),
        migrations.AlterField(
            model_name='socialsmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='erm'),
        ),
        migrations.AlterField(
            model_name='socialsmodel',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Ссылка на сервис'),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='time',
            field=models.CharField(default='11-04-2026 02:21:13', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
