# Generated by Django 6.0 on 2026-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0006_alter_charactersmodel_time_alter_reviewmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='01-01-2026 21:08:31', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='01-01-2026 21:08:31', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
