# Generated by Django 6.0 on 2026-01-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0007_alter_charactersmodel_time_alter_reviewmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на постер'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='01-01-2026 21:15:54', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='01-01-2026 21:15:54', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
