# Generated by Django 6.0 on 2026-04-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0007_alter_socialsmodel_options_socialsmodel_human_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsmodel',
            name='human_name',
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='11-04-2026 02:22:42', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='11-04-2026 02:22:42', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='randommodel',
            name='time',
            field=models.CharField(default='11-04-2026 02:22:42', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='socialsmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Человеческое название сервиса'),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='time',
            field=models.CharField(default='11-04-2026 02:22:42', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
