# Generated by Django 6.0 on 2026-01-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0008_reviewmodel_url_alter_charactersmodel_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=100, verbose_name='Ссылка на арт')),
                ('channel', models.CharField(max_length=100, verbose_name='Ссылка на художника')),
                ('author', models.CharField(max_length=100, verbose_name='Ник художника')),
            ],
            options={
                'verbose_name': 'Референс',
                'verbose_name_plural': 'Референсы',
            },
        ),
        migrations.CreateModel(
            name='SocialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на соцсеть')),
                ('name', models.CharField(max_length=100, verbose_name='Название соцсети')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:08:38', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:08:38', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
