# Generated by Django 6.0 on 2026-01-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0009_refsmodel_socialsmodel_alter_charactersmodel_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на игру в стиме')),
                ('name', models.CharField(max_length=100, verbose_name='Название игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:31:35', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:31:35', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
