# Generated by Django 6.0 on 2026-01-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0010_gamesmodel_alter_charactersmodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:32:42', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на игру в стиме'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:32:42', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
