# Generated by Django 6.0 on 2026-01-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0011_alter_charactersmodel_time_alter_gamesmodel_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Увлечение')),
            ],
            options={
                'verbose_name': 'Увлечение',
                'verbose_name_plural': 'Увлечения',
            },
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:51:01', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 05:51:01', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
