# Generated by Django 6.0 on 2026-01-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0012_hobbymodel_alter_charactersmodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 13:50:30', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 13:50:30', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
