# Generated by Django 6.0 on 2026-01-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0014_preformersmodel_alter_charactersmodel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refsmodel',
            name='character',
            field=models.CharField(default='me', max_length=100, verbose_name='Имя ОС-а'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 14:38:47', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 14:38:47', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
