# Generated by Django 6.0 on 2026-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0015_refsmodel_character_alter_charactersmodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 14:43:57', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='refsmodel',
            name='character',
            field=models.CharField(choices=[('1', 'Селфсона'), ('2', 'Старый скин')], default='Undefined', max_length=100, verbose_name='Имя ОС-а'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 14:43:57', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
