# Generated by Django 6.0 on 2026-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0016_alter_charactersmodel_time_alter_refsmodel_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='02-01-2026 14:44:04', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='02-01-2026 14:44:04', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
