# Generated by Django 6.0 on 2026-01-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0017_alter_charactersmodel_time_alter_reviewmodel_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('url', models.CharField(max_length=100, verbose_name='Имя страницы в urls.py')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='time',
            field=models.CharField(default='03-01-2026 01:17:36', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='time',
            field=models.CharField(default='03-01-2026 01:17:36', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
