# Generated by Django 6.0 on 2026-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0018_pagesmodel_alter_charactersmodel_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersmodel',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='05-01-2026 22:02:41', max_length=50, verbose_name='Время создания рецензии'),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='expression',
            field=models.CharField(max_length=100, verbose_name='Исходное выражение'),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='result',
            field=models.IntegerField(verbose_name='Результат операции'),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='05-01-2026 22:02:41', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на игру'),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Путь относительно главной'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=models.TextField(verbose_name='Текст рецензии'),
        ),
    ]
