# Generated by Django 6.0 on 2026-01-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0019_remove_charactersmodel_time_remove_reviewmodel_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название промпта')),
                ('prompt', models.TextField(verbose_name='Промпт')),
                ('description', models.CharField(max_length=100, verbose_name='Описание промпта')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
            },
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='06-01-2026 01:09:54', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='06-01-2026 01:09:54', max_length=50, verbose_name='Время создания рецензии'),
        ),
    ]
