# Generated by Django 6.0 on 2026-01-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0020_promptsmodel_alter_calchistory_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsmodel',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Статус одобрения'),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='06-01-2026 02:54:01', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='06-01-2026 02:54:01', max_length=50, verbose_name='Время создания рецензии'),
        ),
    ]
