# Generated by Django 6.0 on 2026-01-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0021_promptsmodel_is_approved_alter_calchistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='06-01-2026 03:04:15', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='06-01-2026 03:04:15', max_length=50, verbose_name='Время создания рецензии'),
        ),
    ]
