# Generated by Django 6.0 on 2026-01-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0022_alter_calchistory_time_alter_reviewmodel_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='06-01-2026 03:09:18', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='06-01-2026 03:09:18', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='06-01-2026 03:09:18', max_length=50, verbose_name='Время создания рецензии'),
        ),
    ]
