# Generated by Django 6.0 on 2026-01-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0023_promptsmodel_created_at_alter_calchistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='06-01-2026 04:29:57', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='06-01-2026 04:29:57', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=models.TextField(default='', verbose_name='Текст рецензии'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='06-01-2026 04:29:57', max_length=50, verbose_name='Время создания рецензии'),
        ),
    ]
