# Generated by Django 6.0 on 2026-01-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0024_alter_calchistory_time_alter_promptsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='06-01-2026 04:40:54', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='06-01-2026 04:40:54', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='06-01-2026', max_length=50, verbose_name='Время создания рецензии'),
        ),
    ]
