# Generated by Django 6.0 on 2026-01-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0026_alter_calchistory_time_alter_promptsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='genre',
            field=models.CharField(choices=[('1', 'Аниме'), ('2', 'Фильм'), ('3', 'Сериал'), ('4', 'Мультик')], null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='07-01-2026 03:40:08', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='07-01-2026 03:40:08', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='07-01-2026', max_length=50, verbose_name='Дата создания рецензии'),
        ),
    ]
