# Generated by Django 6.0 on 2026-01-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0027_reviewmodel_genre_alter_calchistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='07-01-2026 03:49:26', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='07-01-2026 03:49:26', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='genre',
            field=models.CharField(choices=[('Аниме', 'Аниме'), ('Фильм', 'Фильм'), ('Сериал', 'Сериал'), ('Мультик', 'Мультик')], null=True, verbose_name='Жанр'),
        ),
    ]
