# Generated by Django 6.0 on 2026-01-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0030_alter_calchistory_time_alter_promptsmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='10-01-2026 03:37:30', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='10-01-2026 03:37:30', max_length=50, verbose_name='Время отправки промпта'),
        ),
    ]
