# Generated by Django 6.0 on 2026-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0031_alter_calchistory_time_alter_promptsmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=500, verbose_name='Изначальная строка')),
                ('answer', models.JSONField(blank=True, default=list, verbose_name='Разделелённая строка')),
                ('time', models.CharField(default='14-01-2026 23:23:20', editable=False, max_length=50, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'История строк',
                'verbose_name_plural': 'История строк',
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='14-01-2026 23:23:20', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='14-01-2026 23:23:20', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='14-01-2026', max_length=50, verbose_name='Дата создания рецензии'),
        ),
    ]
