# Generated by Django 6.0 on 2026-01-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0032_strhistory_alter_calchistory_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strhistory',
            name='answer',
        ),
        migrations.AddField(
            model_name='strhistory',
            name='digits',
            field=models.JSONField(blank=True, default=list, verbose_name='Цифры'),
        ),
        migrations.AddField(
            model_name='strhistory',
            name='errors',
            field=models.JSONField(blank=True, default=list, verbose_name='Исправленные слова'),
        ),
        migrations.AddField(
            model_name='strhistory',
            name='others',
            field=models.JSONField(blank=True, default=list, verbose_name='Прочее'),
        ),
        migrations.AddField(
            model_name='strhistory',
            name='words',
            field=models.JSONField(blank=True, default=list, verbose_name='Оригинальные слова'),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='time',
            field=models.CharField(default='17-01-2026 16:05:54', editable=False, max_length=50, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='created_at',
            field=models.CharField(default='17-01-2026 16:05:54', max_length=50, verbose_name='Время отправки промпта'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_time',
            field=models.CharField(default='17-01-2026', max_length=50, verbose_name='Дата создания рецензии'),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='time',
            field=models.CharField(default='17-01-2026 16:05:54', editable=False, max_length=50, verbose_name='Время создания'),
        ),
    ]
